env: 
  es2022: true
  jest: true
parser: '@typescript-eslint/parser'
plugins: 
  - jest
  - simple-import-sort
  - import
extends: 
  - eslint:recommended
  - plugin:@typescript-eslint/recommended
  - plugin:jest/recommended
  - next/core-web-vitals
  - prettier
rules: 
  import/newline-after-import: error
  import/no-default-export: error
  simple-import-sort/imports: warn
  simple-import-sort/exports: error

overrides: 
  # 一部ルールを除外する
  # default exportの使用が必須なところのみoffにする
  - files: 
       - "src/pages/**/*.tsx"
       - "src/pages/**/*.ts"
    rules: 
      'import/no-default-export': 'off'
  -  files: '**/*.stories.tsx'
     rules: 
        'arrow-body-style': 'off'
        'import/no-default-export': 'off'