env: 
  es2022: true
  jest: true
parser: '@typescript-eslint/parser'
plugins: 
  - jest
  - simple-import-sort
  - import
extends: 
  - eslint:recommended
  - plugin:@typescript-eslint/recommended
  - plugin:jest/recommended
  - next/core-web-vitals
  - prettier
rules: 
  import/newline-after-import: error
  import/no-default-export: error
  simple-import-sort/imports: warn
  simple-import-sort/exports: error
